// src/components/Stat.vue
<template>
<div class="stat">
  <div v-if="data.image" class="stat_bg">
    <div class="stat_bg_wrap">
      <div class="stat_bg_prlx" v-prlx="{ fromBottom: true }">
      <!-- <div> -->
        <g-image v-if="data.image" class="stat_bg_img stat_bg_img-landscape" :src="data.image"/>
        <g-image v-if="data.imagePt" class="stat_bg_img stat_bg_img-portrait" :src="data.imagePt"/>
      </div>
    </div>
  </div>
  <div class="container pt-5 pb-5">
    <div class="row justify-content-center">
      <div v-for="item in data.items" :key="item.id" :class="`stat_col col-12 col-lg-${colWidth}`">
        <div class="stat_item text-center">
          <div class="h3 stat_title" v-if="item.title">{{ item.title }}</div>
          <p class="stat_paragraph" v-if="item.paragraph">
            <vue-markdown>{{item.paragraph}}</vue-markdown>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</template>

<script>
import VueMarkdown from 'vue-markdown'

import Vue from 'vue'
import VuePrlx from 'vue-prlx'
Vue.use(VuePrlx);

export default {
    props: {
        statData: {
          type: Object,
          required: true
        }
    },
    components: {
      VueMarkdown
    },
    created() {
      const cols = 12;
      // this.data = this.$props.statData
      this.colWidth = cols;

      if (this.data.items.length) {
        this.colWidth = Math.floor(cols/this.data.items.length);
      }
    },
    mounted() {
      // debugger
    },
    computed: {
      data() {
        return this.$props.statData
      }
    },
}
</script>

<style scoped lang="scss">
@import "assets/styles/base.scss";
.stat {
  color: $white;
  position: relative;
  background-color: $black;
  &_col {}
  &_paragraph {}
  &_bg {
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
    &_prlx {
      transition: none!important;
    }
    &_img {
      width: 100%;
      &-portrait {
        display: none;
      }
      @include media-breakpoint-down(md) {
        @media (orientation: portrait) {
          &-landscape {
            display: none;
          }
          &-portrait {
            display: block;
          }
        }
      }
    }
    &_wrap {
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      width: 100%;
      &:after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba($dark, .4);
      }
    }
  }
  @include media-breakpoint-down(lg) {}
}

</style>

// src/components/Stat/Stat.tsx
import ReactMarkdown from 'react-markdown';
import type { StatData } from '@/types/content';

interface Props {
  statData: StatData;
}

export default function Stat({ statData }: Props) {
  const colWidth = statData.items.length ? Math.floor(12 / statData.items.length) : 12;
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

  return (
    <div className="stat">
      {statData.image && (
        <div className="stat_bg">
          <div className="stat_bg_wrap">
            {statData.imagePt && (
              <img
                className="stat_bg_img stat_bg_img-portrait"
                src={`${basePath}${statData.imagePt}`}
                alt="Vinnytsia JS - UA Frontend Conference"
                loading="lazy"
                decoding="async"
              />
            )}
            <div className="stat_bg_prlx">
              {statData.image && (
                <img
                  className="stat_bg_img stat_bg_img-landscape"
                  src={`${basePath}${statData.image}`}
                  alt="Vinnytsia JS - UA Frontend Conference"
                  loading="lazy"
                  decoding="async"
                />
              )}
            </div>
          </div>
        </div>
      )}
      <div className="container pt-6 pb-6">
        <div className="row justify-content-center">
          {statData.items.map((item, index) => (
            <div
              key={index}
              className={`stat_col col-12 col-lg-${colWidth}`}
            >
              <div className="stat_item text-center">
                {item.title && (
                  <div className="h3 stat_title mb-2 mb-lg-3">
                    <ReactMarkdown components={{ p: ({ children }) => <span>{children}</span> }}>{item.title}</ReactMarkdown>
                  </div>
                )}
                {item.paragraph && (
                  <div className="stat_paragraph">
                    <ReactMarkdown>{item.paragraph}</ReactMarkdown>
                  </div>
                )}
                {index !== statData.items.length - 1 && (
                  <hr className="stat_hr bg-light w-25 my-4" />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
