// src/components/PageTitle.vue
<template>
<div class="page-title text-center">
  <h2 v-if="$props.title">{{ $props.title }}</h2>
  <h6 v-if="$props.subtitle">{{ $props.subtitle }}</h6>
</div>
</template>

<script>
export default {
    props: {
        title: {
          type: String,
          required: false
        },
        subtitle: {
          type: String,
          required: false
        }
    },
    methods: {
    },
    mounted() {
      // debugger
    },
    methods: {},
}
</script>

<style scoped lang="scss">
@import "assets/styles/base.scss";
.page-title {
  @include media-breakpoint-down(lg) {}
}

</style>

// src/components/PageTitle/PageTitle.tsx
interface Props {
  title?: string;
  subtitle?: string;
  id?: string;
  className?: string;
}

export default function PageTitle({ title, subtitle, id, className }: Props) {
  return (
    <div className={`page-title text-center${className ? ' ' + className : ''}`} id={id}>
      {title && <h2 className="h2">{title}</h2>}
      {subtitle && <h4 className="h5">{subtitle}</h4>}
    </div>
  );
}
