// src/components/About.vue
<template>
  <div class="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 align-self-center text-center">
          <div class="about_descrition">
            <h1 class="font-weight-bold">{{ data.titleI18N[lang] }}</h1>
            <p class="my-4">{{ data.paragraph }}</p>
            <a :href="data.link" class="btn btn-primary my-2 my-sm-0">{{ data.linkTitle }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    lang: {
      type: String,
      required: true
    },
    aboutData: {
      type: Object,
      required: true
    }
  },
  created() {
    this.data = this.$props.aboutData;
  },
  mounted() {
    // debugger
  },
  methods: {}
};
</script>

<style scoped lang="scss">
@import "assets/styles/base.scss";
.about {
  width: 100%;
  &_logo {
    max-width: 100%;
  }
  @include media-breakpoint-down(lg) {
  }
}
</style>

// src/components/About/About.tsx
import type { AboutData } from '@/types/content';

interface Props {
  aboutData: AboutData;
}

export default function About({ aboutData }: Props) {
  return (
    <div className="about">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-lg-8 align-self-center text-center">
            <div className="about_descrition">
              <h1 className="font-weight-bold">{aboutData.title}</h1>
              <p className="my-4">{aboutData.paragraph}</p>
              <a href={aboutData.link} className="btn btn-primary my-2 my-sm-0">
                {aboutData.linkTitle}
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
