// src/pages/Policy.vue
<template>
  <Layout>
    <div class="layer layer-content">
      <section>
        <div class="container">
          <div class="row">
            <div class="col text-center">
              <div class="btn-group">
                <button class="btn btn-secondary policy_btn-lang flex align-items-center" @click="toggleLang('EN')"><img class="flag" src="../../assets/images/flags/en.svg"><span class="label">EN</span></button>
                <button class="btn btn-secondary policy_btn-lang flex align-items-center" @click="toggleLang('UA')"><img class="flag" src="../../assets/images/flags/ua.svg"><span class="label">UA</span></button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="section-vh-100">
        <div class="position-relative">
          <div class="container">
            <div class="row">
              <div class="col">
                <div class="policy_content-en">
                  <page-title class="pt-5 pb-5" :title="$page.policyData.title"></page-title>
                  <div class="text-center pb-5">
                    <vue-markdown>{{ $page.policyData.description }}</vue-markdown>
                  </div>
                </div>
                <div class="policy_content-ua">
                    <page-title class="pt-5 pb-5" :title="$page.policyData.titleUA"></page-title>
                    <div class="text-center pb-5">
                      <vue-markdown>{{ $page.policyData.descriptionUA }}</vue-markdown>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <hr>
      <section class="position-relative pb-5">
        <div class="anchor-id" id="contact"></div>
        <page-title class="pt-5 pb-3" title="Contact Us"></page-title>
        <contact-us :contactUsData="{}" :socialIconsData="$page.pageData.nav"></contact-us>
      </section>
    </div>
  </Layout>
</template>

<page-query>
query Policy {
  policyData: policy (path: "/content/policy/policy") {
    title
    titleUA
    description
    descriptionUA
  }
  pageData: conf (path: "/content/conf/vinnytsiajs-2020") {
    nav {
      button {
        active
        src
        title
      }
      items {
        active
        src
        title
      }
      socialicons {
        items {
          active
          icon
          src
          title
        }
      }
    }
    title
  }
}

</page-query>

<script>
import PageTitle from "@/components/PageTitle";
import ContactUs from "@/components/ContactUs";
import VueMarkdown from "vue-markdown";

export default {
  metaInfo: {
    title: 'Policy'
  },
  components: {
    PageTitle,
    ContactUs,
    VueMarkdown
  },
  mounted() {
    // console.log('this.$page.pageData ::: ', this.$page.pageData)
    // debugger
    // window.scroll(0,1)
  },
  methods: {
    toggleLang(lang) {
      document.querySelector('html').setAttribute('page-lang', lang);
    }
  },
}
</script>

<style lang="scss">
    @import "assets/styles/base.scss";
    
    .layout .vjs-navbar {
      background-color: rgba(38, 38, 38, 0.7) !important;
    }
</style>

<style scoped lang="scss">
  @import "assets/styles/base.scss";

  html,
  html[page-lang=EN] {
    .policy_content {
      &-en {
        opacity: block;
      }
      &-ua {
        display: none;
      }
    }
  }

  html[page-lang=UA] {
    .policy_content {
      &-en {
        display: none;
      }
      &-ua {
        display: block;
      }
    }
  }

  .policy {
    &_btn-lang {
      border-top-left-radius: 0;
      border-top-right-radius: 0;
      .flag {
        width: 1.5em;
        height: 1.5em;
        margin-right: 0.5em;
      }
    }
  }

  @include media-breakpoint-down(md) {
    .layout {
      padding-top: 72px;
    }
  }

</style>

// src/pages/policy.tsx
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import DefaultLayout from '@/layouts/DefaultLayout';
import PageTitle from '@/components/PageTitle/PageTitle';
import ContactUs from '@/components/ContactUs/ContactUs';
import ReactMarkdown from 'react-markdown';
import { getConferenceData, getPolicyData } from '@/lib/content';
import type { NavData, PolicyData } from '@/types/content';

interface Props {
  navData: NavData;
  policyData: PolicyData;
}

const PolicyPage: NextPage<Props> = ({ navData, policyData }) => {
  const [lang, setLang] = useState<'EN' | 'UA'>('EN');
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

  return (
    <DefaultLayout navData={navData}>
      <Head>
        <title>Policy - VinnytsiaJS</title>
      </Head>

      <div className="layer layer-content">
        <section>
          <div className="container">
            <div className="row">
              <div className="col text-center">
                <div className="btn-group">
                  <button
                    className="btn btn-secondary policy_btn-lang flex align-items-center"
                    onClick={() => setLang('EN')}
                  >
                    <img className="flag" src={`${basePath}/assets/images/flags/en.svg`} alt="EN" />
                    <span className="label">EN</span>
                  </button>
                  <button
                    className="btn btn-secondary policy_btn-lang flex align-items-center"
                    onClick={() => setLang('UA')}
                  >
                    <img className="flag" src={`${basePath}/assets/images/flags/ua.svg`} alt="UA" />
                    <span className="label">UA</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section-vh-100">
          <div className="position-relative">
            <div className="container">
              <div className="row">
                <div className="col">
                  {lang === 'EN' ? (
                    <div className="policy_content-en">
                      <PageTitle className="pt-5 pb-5" title={policyData.title} />
                      <div className="text-center pb-5">
                        <ReactMarkdown>{policyData.description}</ReactMarkdown>
                      </div>
                    </div>
                  ) : (
                    <div className="policy_content-ua">
                      <PageTitle className="pt-5 pb-5" title={policyData.titleUA} />
                      <div className="text-center pb-5">
                        <ReactMarkdown>{policyData.descriptionUA}</ReactMarkdown>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </section>

        <hr />

        <section className="position-relative pb-5">
          <div className="anchor-id" id="contact"></div>
          <PageTitle className="pt-5 pb-3" title="Contact Us" />
          <ContactUs contactUsData={{}} socialIconsData={navData} />
        </section>
      </div>
    </DefaultLayout>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const confData = getConferenceData();
  const { frontmatter } = getPolicyData();

  return {
    props: {
      navData: confData.nav,
      policyData: frontmatter,
    },
  };
};

export default PolicyPage;
