// src/components/Speakers/Speakers.tsx
import ReactMarkdown from 'react-markdown';
import type { ConferenceSpeakers } from '@/types/content';

interface Props {
  speakersData: ConferenceSpeakers;
  className?: string;
}

export default function Speakers({ speakersData, className }: Props) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

  return (
    <div className={`speakers${className ? ' ' + className : ''}`}>
      <div className="container">
        <div className="row justify-content-center align-items-top">
          {speakersData.items.map((item, index) => (
            <div key={index} className="stat_col col-md-6 col-lg-4">
              <div id={item.fields.id} className="speakers_item text-center px-1 mb-5">
                {item.fields.image && (
                  <img
                    className="speakers_img"
                    src={`${basePath}${item.fields.image}`}
                    alt={item.fields.title}
                  />
                )}
                {item.fields.name && (
                  <h3 className="h3 my-3">{item.fields.name}</h3>
                )}
                <div>
                  <span className="lead text-warning">{item.fields.company}</span>
                </div>
                <div className="speakers_item_caption">
                  {item.fields.title && <span>{item.fields.title}</span>}
                  {item.fields.city && <span>, {item.fields.city}</span>}
                  {item.fields.country && <span>, {item.fields.country}</span>}
                </div>
                {item.fields.socialLinks?.length > 0 && item.fields.socialLinks[0]?.src && (
                  <div className="contact-us_social-icons navbar-expand d-inline-block h4 mt-3 my-0">
                    <ul className="social-icons list-unstyled navbar-nav">
                      {item.fields.socialLinks.map((socialLink, sIndex) => (
                        <li key={sIndex} className="social-icons_item nav-item">
                          {socialLink.src && (
                            <a
                              target="_blank"
                              rel="noopener noreferrer"
                              className="social-icons_link nav-link"
                              href={socialLink.src}
                            >
                              <i className={socialLink.icon}></i>
                            </a>
                          )}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {item.fields.bio && (
                  <div className="mt-3 text-left">
                    <div>
                      <ReactMarkdown>{item.fields.bio}</ReactMarkdown>
                    </div>
                    <div className="text-center py-3">
                      {item.talk?.id ? (
                        <a
                          className="btn btn-outline-primary btn-sm"
                          href={`#${item.talk.id}`}
                        >
                          Talk Info
                        </a>
                      ) : (
                        <span className="btn btn-outline-secondary btn-sm">
                          Talk Will Be Announced
                        </span>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/components/Speakers.vue
<template>
  <div class="speakers">
    <div class="container">
      <div class="row justify-content-center align-items-top">
        <div
          v-for="item in data.items"
          :key="item.id"
          class="stat_col col-md-6 col-lg-4"
        >
          <div :id="item.fields.id" class="speakers_item text-center px-1 mb-5">
            <g-image
              v-if="item.fields.image"
              class="speakers_img"
              :src="item.fields.image"
              :alt="item.fields.title"
            />
            <h3 class="h3 my-3" v-if="item.fields.name">{{ item.fields.name }}</h3>
            <div>
              <span class="lead text-warning">{{ item.fields.company }}</span>
            </div>
            <div class="speakers_item_caption">
              <span v-if="item.fields.title">{{ item.fields.title }}</span>
              <span v-if="item.fields.city">, {{ item.fields.city }}</span>
              <span v-if="item.fields.country">, {{ item.fields.country }}</span>
            </div>
            <div
              v-if="item.fields.socialLinks.length && item.fields.socialLinks[0].src"
              class="contact-us_social-icons navbar-expand d-inline-block h4 mt-3 my-0">
              <ul class="social-icons list-unstyled navbar-nav">
                <li
                  v-for="socialLink in item.fields.socialLinks"
                  :key="socialLink.id"
                  class="social-icons_item nav-item"
                >
                  <a
                    target="_blank"
                    class="social-icons_link nav-link"
                    v-if="socialLink.src"
                    :href="socialLink.src"
                  >
                    <i :class="socialLink.icon"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div v-if="item.fields.bio" class="mt-3 text-left">
              <span>
                <vue-markdown>{{ item.fields.bio }}</vue-markdown>
              </span>
              <div class="text-center py-3">
                <a 
                  v-if="item.talk.id" 
                  class="btn btn-outline-primary btn-sm" 
                  :href="`#${item.talk.id}`">Talk Info
                </a>
                <span 
                  v-else
                  class="btn btn-outline-secondary btn-sm"
                  > Talk Will Be Announced
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import VueMarkdown from "vue-markdown";

export default {
  props: {
    mode: {
      type: String,
      required: false
    },
    speakersData: {
      type: Object,
      required: true
    }
  },
  components: {
    VueMarkdown
  },
  mounted() {
    // debugger
  },
  computed: {
    data() {
      return this.$props.speakersData;
    }
  }
};
</script>

<style scoped lang="scss">
@import "assets/styles/base.scss";
.speakers {
  &_img {
    max-width: 100%;
    border-radius: 50%;
  }
  &_item {
    position: relative;
    z-index: 1;
    &:hover:before {
      opacity: 1;
    }
    &:before {
      content: '';
      @include transition(all ease-in-out 0.2s);
      position: absolute;
      display: block;
      border-radius: $border-radius;
      top: -1em;
      bottom: -1em;
      left: -1em;
      right: -1em;
      z-index: -1;
      background: rgba($dark, 0.05);
      opacity: 0;
    }
    &_caption {
      font-weight: 500;
    }
  }
  @include media-breakpoint-down(lg) {
  }
}
</style>
