// src/components/ContactUs.vue
<template>
  <div class="contact-us">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-6">
          <div class="text-center pb-4">
            <p
              class="h5 font-weight-normal"
              >Follow us on social media for more information and news about the conference. <br/>See you soon!
            </p>
            <div class="contact-us_social-icons navbar-expand d-inline-block h4 my-3">
              <social-icons :socialIconsData="this.socialData.socialicons"></social-icons>
            </div>
            <div class="mb-3">
              <a class="btn btn-secondary py-1 m-1" :href="/policy/">Policy</a>
              <a class="btn btn-secondary py-1 m-1" href="https://vinnytsiajs.org/docs/Code_of_Conduct_-_VinnytsiaJS.pdf" target="_blank">Code of Conduct</a>
            </div>
            <ul class="list-unstyled">
              <!-- <li>
                <span>Partnership:</span>
                <a href="tel:+380636310436">+38 063 63 104 36</a>
              </li>
              <li>
                <span>Transfer:</span>
                <a href="tel:+380688186200">+38 068 818 62 00</a>
              </li> -->
              <li>
                <a href="mailto:info@vinnytsiajs.org">info@vinnytsiajs.org</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>


<script>
import SocialIcons from "@/components/SocialIcons";

export default {
  components: {
    SocialIcons
  },
  props: {
    contactUsData: {
      type: Object,
      required: true
    },
    socialIconsData: {
      type: Object,
      required: false
    }
  },
  mounted() {
    // debugger
  },
  computed: {
    data() {
      return this.$props.contactUsData;
    },
    socialData() {
      return this.$props.socialIconsData;
    }
  }
};
</script>

<style scoped lang="scss">
@import "assets/styles/base.scss";

.contact-us {
  &_social-icons {
    .social-icons {
    }
  }
  @include media-breakpoint-down(lg) {
  }
}
</style>

// src/components/ContactUs/ContactUs.tsx
import SocialIcons from '@/components/SocialIcons/SocialIcons';
import type { NavData } from '@/types/content';

interface Props {
  contactUsData: Record<string, unknown>;
  socialIconsData: NavData;
}

export default function ContactUs({ contactUsData, socialIconsData }: Props) {
  return (
    <div className="contact-us">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-12 col-md-6">
            <div className="text-center pb-4">
              <p className="h5 font-weight-normal">
                Follow us on social media for more information and news about the conference.
                <br />See you soon!
              </p>
              <div className="contact-us_social-icons navbar-expand d-inline-block h4 my-3">
                <SocialIcons socialIconsData={socialIconsData.socialicons} />
              </div>
              <div className="mb-3">
                <a className="btn btn-secondary py-1 m-1" href="/policy/">Policy</a>
                <a
                  className="btn btn-secondary py-1 m-1"
                  href="https://vinnytsiajs.org/docs/Code_of_Conduct_-_VinnytsiaJS.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Code of Conduct
                </a>
              </div>
              <ul className="list-unstyled">
                <li>
                  <a href="mailto:info@vinnytsiajs.org">info@vinnytsiajs.org</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
